---
- name: "Preflight - Fail if target host is not stable for this Role."
  ansible.builtin.fail:
    msg: "This role is not stable for the target operating system, {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
  when: (ansible_distribution is not defined) or
        (ansible_distribution_version is not defined) or
        (ansible_distribution+" "+ansible_distribution_major_version not in upgrade_stable_os)

- name: "Include Package Manager specific Playbook."
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}.yml"

- name: "Restart Services."
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ service_restarts }}"
  when:
    - ((reboot_hint is not defined) or reboot_hint is defined and not (upgrade_unattended_reboot | bool))
    - (service_restarts is defined and service_restarts | length)
    - (upgrade_restart_services | bool)
    - (item not in upgrade_restart_services_blacklist)

- name: "Reboot Server."
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 300
    post_reboot_delay: "{{ patchday_sleep | default('10') }}"
    msg: "Reboot triggered by Ansible"
  when:
    - (reboot_hint is defined and reboot_hint | bool)
    - (upgrade_unattended_reboot | bool) or (upgrade_force_reboot | bool)

- name: "Include Reporting Playbook."
  ansible.builtin.include_tasks: "report.yml"
  when: upgrade_reporting_enable | bool
